#!/bin/sh

while [ ! -d /workspace/thulijaplatform/tcodegen ]; do
    sleep 5
done

cd /workspace/thulijaplatform/tcodegen
exec mvn spring-boot:run \
    -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
