#!/bin/sh

STUDIO_DIR=/workspace/thulijaplatform/tcodegen/studio

while [ ! -d "$STUDIO_DIR" ]; do
    sleep 5
done

cd "$STUDIO_DIR"

if [ ! -d "node_modules" ]; then
    npm install
fi

exec ng serve --host 0.0.0.0 \
    2>&1 | tee "$STUDIO_DIR/angular.log"
